# **Experiment_16**

**Aim: Implement Strassen’s Matrix Multiplication
Test Output for 2×2 & 4×4 matrices.**

**Algorithm: Strassen Matrix Multiplication**

Algorithm Strassen(A, B)

Step 1: If matrix size = 1
        return A * B

Step 2: Divide matrix A and B into 4 submatrices

        A11  A12
        A21  A22

        B11  B12
        B21  B22

Step 3: Compute 7 products

        M1 = (A11 + A22)(B11 + B22)
        M2 = (A21 + A22)(B11)
        M3 = (A11)(B12 − B22)
        M4 = (A22)(B21 − B11)
        M5 = (A11 + A12)(B22)
        M6 = (A21 − A11)(B11 + B12)
        M7 = (A12 − A22)(B21 + B22)

Step 4: Compute result matrices

        C11 = M1 + M4 − M5 + M7
        C12 = M3 + M5
        C21 = M2 + M4
        C22 = M1 − M2 + M3 + M6

Step 5: Combine C11 C12 C21 C22

Step 6: Return Result Matrix

In [1]:
import numpy as np

def split(matrix):
    row, col = matrix.shape
    r, c = row//2, col//2
    return matrix[:r,:c], matrix[:r,c:], matrix[r:,:c], matrix[r:,c:]

def strassen(A, B):

    if len(A) == 1:
        return A * B

    A11, A12, A21, A22 = split(A)
    B11, B12, B21, B22 = split(B)

    M1 = strassen(A11 + A22, B11 + B22)
    M2 = strassen(A21 + A22, B11)
    M3 = strassen(A11, B12 - B22)
    M4 = strassen(A22, B21 - B11)
    M5 = strassen(A11 + A12, B22)
    M6 = strassen(A21 - A11, B11 + B12)
    M7 = strassen(A12 - A22, B21 + B22)

    C11 = M1 + M4 - M5 + M7
    C12 = M3 + M5
    C21 = M2 + M4
    C22 = M1 - M2 + M3 + M6

    top = np.hstack((C11, C12))
    bottom = np.hstack((C21, C22))

    return np.vstack((top, bottom))

In [2]:
import numpy as np

def split(matrix):
    row, col = matrix.shape
    r, c = row//2, col//2
    return matrix[:r,:c], matrix[:r,c:], matrix[r:,:c], matrix[r:,c:]

def strassen(A, B):

    if len(A) == 1:
        return A * B

    A11, A12, A21, A22 = split(A)
    B11, B12, B21, B22 = split(B)

    M1 = strassen(A11 + A22, B11 + B22)
    M2 = strassen(A21 + A22, B11)
    M3 = strassen(A11, B12 - B22)
    M4 = strassen(A22, B21 - B11)
    M5 = strassen(A11 + A12, B22)
    M6 = strassen(A21 - A11, B11 + B12)
    M7 = strassen(A12 - A22, B21 + B22)

    C11 = M1 + M4 - M5 + M7
    C12 = M3 + M5
    C21 = M2 + M4
    C22 = M1 - M2 + M3 + M6

    top = np.hstack((C11, C12))
    bottom = np.hstack((C21, C22))

    return np.vstack((top, bottom))


def input_matrix(n):
    matrix = []
    for i in range(n):
        row = list(map(int, input().split()))
        matrix.append(row)
    return np.array(matrix)


while True:

    print("\n--- STRASSEN MATRIX MULTIPLICATION ---")
    print("1. 2x2 Matrix")
    print("2. 4x4 Matrix")
    print("3. Exit")

    ch = int(input("Enter choice: "))

    if ch == 1:

        n = 2
        print("Enter Matrix A:")
        A = input_matrix(n)

        print("Enter Matrix B:")
        B = input_matrix(n)

        result = strassen(A,B)

        print("\nResult Matrix:")
        print(result)

    elif ch == 2:

        n = 4
        print("Enter Matrix A:")
        A = input_matrix(n)

        print("Enter Matrix B:")
        B = input_matrix(n)

        result = strassen(A,B)

        print("\nResult Matrix:")
        print(result)

    elif ch == 3:
        break

    else:
        print("Invalid Choice")


--- STRASSEN MATRIX MULTIPLICATION ---
1. 2x2 Matrix
2. 4x4 Matrix
3. Exit
Enter choice: 1
Enter Matrix A:
1 2
3 4
Enter Matrix B:
5 6
7 8

Result Matrix:
[[19 22]
 [43 50]]

--- STRASSEN MATRIX MULTIPLICATION ---
1. 2x2 Matrix
2. 4x4 Matrix
3. Exit
Enter choice: 2
Enter Matrix A:
1 2 3 4
5 6 7 8
9 1 2 3
4 5 6 7
Enter Matrix B:
1 0 2 1
3 1 0 2
4 2 1 3
1 3 2 0

Result Matrix:
[[23 20 13 14]
 [59 44 33 38]
 [23 14 26 17]
 [50 38 28 32]]

--- STRASSEN MATRIX MULTIPLICATION ---
1. 2x2 Matrix
2. 4x4 Matrix
3. Exit
Enter choice: 3
